// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWUjmemS-IXor8nvfWUSAEdEterJIRpLs',
    appId: '1:417041453280:web:6b5d493da6f83b7c8dc085',
    messagingSenderId: '417041453280',
    projectId: 'kedeapp',
    authDomain: 'kedeapp.firebaseapp.com',
    storageBucket: 'kedeapp.firebasestorage.app',
    measurementId: 'G-DTTVRJEE6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZTRnBf8vauHmMc_yorS8GEMxAewhFaus',
    appId: '1:417041453280:android:fe97722f94dd4e9b8dc085',
    messagingSenderId: '417041453280',
    projectId: 'kedeapp',
    storageBucket: 'kedeapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHNbpf-XdSzqoY6OO-gOTSZqhZWoFHjXI',
    appId: '1:417041453280:ios:96b0908c3b31b9ae8dc085',
    messagingSenderId: '417041453280',
    projectId: 'kedeapp',
    storageBucket: 'kedeapp.firebasestorage.app',
    iosBundleId: 'com.example.kede',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHNbpf-XdSzqoY6OO-gOTSZqhZWoFHjXI',
    appId: '1:417041453280:ios:96b0908c3b31b9ae8dc085',
    messagingSenderId: '417041453280',
    projectId: 'kedeapp',
    storageBucket: 'kedeapp.firebasestorage.app',
    iosBundleId: 'com.example.kede',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWUjmemS-IXor8nvfWUSAEdEterJIRpLs',
    appId: '1:417041453280:web:215aead725bf9a1f8dc085',
    messagingSenderId: '417041453280',
    projectId: 'kedeapp',
    authDomain: 'kedeapp.firebaseapp.com',
    storageBucket: 'kedeapp.firebasestorage.app',
    measurementId: 'G-V00PWDKEN8',
  );
}